import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Eye, EyeOff } from 'lucide-react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getSupabaseClient } from '@/services/supabase';
import { SettingsHeader, settingsPalette as p, settingsStyles as s } from '@/components/settings-ui';

export default function ChangePasswordScreen() {
  const client = getSupabaseClient(); const [email, setEmail] = useState(''); const [hasPassword, setHasPassword] = useState<boolean | null>(null); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [visible, setVisible] = useState({ current: false, next: false, confirm: false }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { void (async () => { if (!client) { setHasPassword(null); return; } const { data, error: userError } = await client.auth.getUser(); if (userError || !data.user) { setError(userError?.message || 'Account could not load.'); setHasPassword(null); return; } setEmail(data.user.email || ''); const providers = data.user.app_metadata?.providers; const emailIdentity = data.user.identities?.some((identity) => identity.provider === 'email'); setHasPassword(Boolean(emailIdentity || providers?.includes('email') || data.user.user_metadata?.password_set === true)); })(); }, [client]);
  const field = (label: string, key: 'current' | 'next' | 'confirm', value: string, setValue: (value: string) => void, placeholder: string) => <View style={s.field}><Text style={s.formLabel}>{label}</Text><View style={{ position: 'relative', justifyContent: 'center' }}><TextInput accessibilityLabel={label} value={value} onChangeText={setValue} placeholder={placeholder} placeholderTextColor={p.muted} secureTextEntry={!visible[key]} autoCapitalize="none" style={[s.input, { paddingRight: 50 }]} /><Pressable accessibilityRole="button" accessibilityLabel={visible[key] ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`} onPress={() => setVisible((state) => ({ ...state, [key]: !state[key] }))} style={{ position: 'absolute', right: 12, padding: 8 }}>{visible[key] ? <EyeOff size={19} color={p.muted} /> : <Eye size={19} color={p.muted} />}</Pressable></View></View>;
  const submit = async () => { setError(''); setSuccess(''); if (hasPassword === null || !client) { setError('Account authentication is unavailable right now.'); return; } if (hasPassword && !current) { setError('Enter your current password.'); return; } if (next.length < 8 || !/\d/.test(next)) { setError('Use at least 8 characters and include a number.'); return; } if (next !== confirm) { setError('Passwords do not match.'); return; } setBusy(true); try { if (hasPassword) { const check = await client.auth.signInWithPassword({ email, password: current }); if (check.error) throw check.error; } const user = await client.auth.getUser(); const result = await client.auth.updateUser({ password: next, data: { ...(user.data.user?.user_metadata || {}), password_set: true } }); if (result.error) throw result.error; await client.auth.refreshSession(); setCurrent(''); setNext(''); setConfirm(''); setSuccess(hasPassword ? 'Password updated successfully.' : 'Password set successfully.'); } catch (e) { setError(e instanceof Error ? e.message : 'Password could not be updated.'); } finally { setBusy(false); } };
  return <SafeAreaView style={s.safe} edges={['top', 'left', 'right']}><SettingsHeader title={hasPassword === false ? 'Set a password' : 'Change password'} onBack={() => router.back()} /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.card}><Text style={s.copy}>{hasPassword === false ? 'Your account uses a connected provider. Set a password to also enable email/password sign-in.' : 'Re-enter your current password before choosing a new one.'}</Text>{hasPassword ? field('Current password', 'current', current, setCurrent, 'Current password') : null}{field('New password', 'next', next, setNext, 'At least 8 characters and a number')}{field('Confirm new password', 'confirm', confirm, setConfirm, 'Enter it again')}<Pressable disabled={busy || hasPassword === null} onPress={() => void submit()} style={[s.button, (busy || hasPassword === null) && { opacity: 0.6 }]}>{busy ? <ActivityIndicator color="#FFFFFF" /> : <Text style={s.buttonText}>{hasPassword === false ? 'Set password' : 'Update password'}</Text>}</Pressable>{error ? <Text style={s.error}>{error}</Text> : null}{success ? <Text style={s.success}>{success}</Text> : null}</View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
