import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ShieldCheck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getSupabaseClient } from '@/services/supabase';
import { SettingsHeader, settingsPalette as p, settingsStyles as s } from '@/components/settings-ui';

type Factor = { id: string; friendlyName?: string | null };

export default function AuthenticatorScreen() {
  const client = getSupabaseClient();
  const [factor, setFactor] = useState<Factor | null>(null); const [currentAal, setCurrentAal] = useState<string | null>(null); const [setup, setSetup] = useState<{ id: string; qr: string; secret: string } | null>(null); const [code, setCode] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { if (!client) { setLoading(false); setError('Authentication is unavailable right now.'); return; } setLoading(true); try { const [{ data, error: factorError }, { data: aal, error: aalError }] = await Promise.all([client.auth.mfa.listFactors(), client.auth.mfa.getAuthenticatorAssuranceLevel()]); if (factorError) throw factorError; if (aalError) throw aalError; const verified = data.totp[0]; setFactor(verified ? { id: verified.id, friendlyName: verified.friendly_name } : null); setCurrentAal(aal.currentLevel); } catch (e) { setError(e instanceof Error ? e.message : 'Authenticator status could not load.'); } finally { setLoading(false); } };
  // The loader only reads the stable Supabase client and is intentionally run once on mount.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  const begin = async () => { if (!client) return; setBusy(true); setError(''); setMessage(''); try { const result = await client.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Alalay authenticator' }); if (result.error || !result.data) throw result.error || new Error('Authenticator setup could not start.'); setSetup({ id: result.data.id, qr: result.data.totp.qr_code, secret: result.data.totp.secret }); } catch (e) { setError(e instanceof Error ? e.message : 'Authenticator setup could not start.'); } finally { setBusy(false); } };
  const verify = async () => { if (!client || !setup || !/^\d{6}$/.test(code)) { setError('Enter the 6-digit code from your authenticator app.'); return; } setBusy(true); setError(''); try { const result = await client.auth.mfa.challengeAndVerify({ factorId: setup.id, code }); if (result.error) throw result.error; setSetup(null); setCode(''); setMessage('Authenticator enabled.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'That authenticator code is invalid.'); } finally { setBusy(false); } };
  const disable = async () => { if (!client || !factor || currentAal !== 'aal2') { setError('Complete a two-factor sign-in before disabling the authenticator.'); return; } setBusy(true); setError(''); try { const result = await client.auth.mfa.unenroll({ factorId: factor.id }); if (result.error) throw result.error; setMessage('Authenticator disabled.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Authenticator could not be disabled.'); } finally { setBusy(false); } };
  return <SafeAreaView style={s.safe} edges={['top', 'left', 'right']}><SettingsHeader title="Authenticator" onBack={() => router.back()} /><ScrollView contentContainerStyle={s.content}><View style={s.card}><ShieldCheck size={28} color={p.accent} /><Text style={[s.formLabel, { marginTop: 14 }]}>Two-factor authentication</Text>{loading ? <ActivityIndicator color={p.accent} /> : <><Text style={s.copy}>{factor ? 'Your account requires a 6-digit authenticator code at sign-in.' : 'Add an authenticator app to protect access to your account.'}</Text>{factor ? <><Text style={[s.status, { marginTop: 14 }]}>Enabled{factor.friendlyName ? ` · ${factor.friendlyName}` : ''}</Text><Pressable disabled={busy} onPress={() => void disable()} style={[s.button, { backgroundColor: '#FFF7F6', borderWidth: 1, borderColor: '#F2C6C2' }, busy && { opacity: 0.6 }]}><Text style={[s.buttonText, { color: p.danger }]}>{busy ? 'Working...' : 'Disable authenticator'}</Text></Pressable></> : <Pressable disabled={busy} onPress={() => void begin()} style={[s.button, busy && { opacity: 0.6 }]}>{busy ? <ActivityIndicator color="#FFFFFF" /> : <Text style={s.buttonText}>Set up authenticator</Text>}</Pressable>}</>}</View>{setup ? <View style={[s.card, { marginTop: 16 }]}><Text style={s.formLabel}>Scan this QR code</Text><Image accessibilityLabel="Authenticator setup QR code" source={{ uri: setup.qr }} style={{ width: 190, height: 190, alignSelf: 'center', marginVertical: 14 }} /><Text style={s.copy}>Or enter this setup key manually:</Text><Text selectable style={[s.formLabel, { marginTop: 8 }]}>{setup.secret}</Text><View style={s.field}><Text style={s.formLabel}>6-digit verification code</Text><TextInput accessibilityLabel="Authenticator verification code" value={code} onChangeText={(value) => setCode(value.replace(/\D/g, '').slice(0, 6))} keyboardType="number-pad" inputMode="numeric" autoComplete="one-time-code" style={s.input} /></View><Pressable disabled={busy} onPress={() => void verify()} style={[s.button, busy && { opacity: 0.6 }]}>{busy ? <ActivityIndicator color="#FFFFFF" /> : <Text style={s.buttonText}>Verify and enable</Text>}</Pressable></View> : null}{error ? <Text style={s.error}>{error}</Text> : null}{message ? <Text style={s.success}>{message}</Text> : null}</ScrollView></SafeAreaView>;
}
