import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authenticatedApiRequest } from '@/services/api';
import { SettingsHeader, settingsPalette as p, settingsStyles as s } from '@/components/settings-ui';

type Profile = { name?: string | null; email?: string | null; phone?: string | null; avatar_url?: string | null };
export default function EditProfileScreen() {
  const [profile, setProfile] = useState<Profile>({}); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  useEffect(() => { void authenticatedApiRequest<Profile>('/api/settings/me').then((value) => { setProfile(value); setName(value.name || ''); setPhone(value.phone || ''); }).catch((e) => setError(e instanceof Error ? e.message : 'Profile could not load.')); }, []);
  const initials = (name || 'Alalay user').split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  const save = async () => { if (!name.trim()) { setError('Name is required.'); return; } setSaving(true); setError(''); setSaved(false); try { await authenticatedApiRequest('/api/settings/me', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: name.trim(), phone: phone.trim() || null }) }); setSaved(true); setTimeout(() => router.back(), 500); } catch (e) { setError(e instanceof Error ? e.message : 'Profile could not be saved.'); } finally { setSaving(false); } };
  return <SafeAreaView style={s.safe} edges={['top', 'left', 'right']}><SettingsHeader title="Edit Profile" onBack={() => router.back()} rightAction={<Pressable accessibilityRole="button" onPress={() => void save()}><Text style={{ color: p.accent, fontWeight: '900' }}>Save</Text></Pressable>} /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content}><View style={s.profile}>{profile.avatar_url ? <Image source={{ uri: profile.avatar_url }} style={s.avatar} /> : <View style={s.avatarFallback}><Text style={s.initials}>{initials}</Text></View>}<Text style={s.backNote}>Profile photos are managed by your connected sign-in provider.</Text></View><View style={s.field}><Text style={s.formLabel}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={p.muted} style={s.input} /></View><View style={s.field}><Text style={s.formLabel}>Email address</Text><TextInput value={profile.email || ''} editable={false} style={[s.input, { color: p.muted }]} /></View><View style={s.field}><Text style={s.formLabel}>Phone number</Text><TextInput value={phone} onChangeText={setPhone} placeholder="Optional" placeholderTextColor={p.muted} keyboardType="phone-pad" style={s.input} /></View>{error ? <Text style={s.error}>{error}</Text> : null}{saved ? <Text style={s.success}>Profile saved.</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={[s.button, saving && { opacity: 0.6 }]}>{saving ? <ActivityIndicator color="#FFFFFF" /> : <Text style={s.buttonText}>Save changes</Text>}</Pressable></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
