import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Bell } from 'lucide-react-native';
import { authenticatedApiRequest } from '@/services/api';
import { SettingsHeader, settingsPalette as p, settingsStyles as s } from '@/components/settings-ui';

type Preferences = { bill_reminders: boolean; bill_reminder_days: number; subscription_reminders: boolean; summaries: boolean; overspending_alerts: boolean; budget_thresholds: boolean; savings_milestones: boolean; login_alerts: boolean };
const defaults: Preferences = { bill_reminders: true, bill_reminder_days: 3, subscription_reminders: true, summaries: false, overspending_alerts: true, budget_thresholds: true, savings_milestones: true, login_alerts: true };
const groups = [{ title: 'Finances', rows: [{ key: 'bill_reminders', label: 'Bill due reminders', copy: 'Get reminded before bills are due.' }, { key: 'overspending_alerts', label: 'Low balance / overspending alerts', copy: 'Get notified when balances are low or spending is unusually high.' }, { key: 'budget_thresholds', label: 'Budget threshold reached', copy: "Get notified when you're approaching or reaching your budget limit." }] }, { title: 'Recurring & goals', rows: [{ key: 'subscription_reminders', label: 'Subscription renewal reminders', copy: 'Get reminded before active subscriptions renew.' }, { key: 'savings_milestones', label: 'Savings goal milestones', copy: 'Celebrate progress when you reach savings milestones.' }] }, { title: 'Security', rows: [{ key: 'login_alerts', label: 'New device login alerts', copy: 'Get notified when your account is accessed from a new device.' }] }];
export default function NotificationSettingsScreen() { const [preferences, setPreferences] = useState<Preferences>(defaults); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(''); useEffect(() => { void authenticatedApiRequest<Preferences>('/api/settings/me/notification-preferences').then((value) => setPreferences({ ...defaults, ...value })).catch((e) => setError(e instanceof Error ? e.message : 'Notification preferences could not load.')).finally(() => setLoading(false)); }, []); const toggle = async (key: keyof Preferences) => { if (key === 'bill_reminder_days' || key === 'summaries') return; const next = { ...preferences, [key]: !preferences[key] }; setPreferences(next); setSaving(key); try { await authenticatedApiRequest('/api/settings/me/notification-preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); } catch (e) { setPreferences(preferences); setError(e instanceof Error ? e.message : 'Notification preference could not save.'); } finally { setSaving(''); } }; return <SafeAreaView style={s.safe} edges={['top', 'left', 'right']}><SettingsHeader title="Notifications" onBack={() => router.back()} /><ScrollView contentContainerStyle={s.content}><View style={s.card}><Bell size={24} color={p.accent} /><Text style={[s.profileName, { marginTop: 10, fontSize: 18 }]}>Notification preferences</Text><Text style={[s.copy, { marginTop: 5 }]}>App preferences are saved to your account. Device notification permission is controlled separately by your operating system.</Text></View>{loading ? <View style={s.card}><ActivityIndicator color={p.accent} /></View> : groups.map((group) => <View key={group.title} style={s.subGroup}><Text style={s.sectionLabel}>{group.title}</Text><View style={s.group}>{group.rows.map((row, index) => <View key={row.key} style={[s.toggleRow, index === group.rows.length - 1 && s.rowLast]}><View style={s.toggleCopy}><Text style={s.rowLabel}>{row.label}</Text><Text style={s.rowValue}>{row.copy}</Text></View><Switch accessibilityLabel={row.label} accessibilityRole="switch" value={Boolean(preferences[row.key as keyof Preferences])} onValueChange={() => void toggle(row.key as keyof Preferences)} disabled={saving === row.key} trackColor={{ false: p.line, true: p.accentPale }} thumbColor={preferences[row.key as keyof Preferences] ? p.accent : '#FFFFFF'} style={s.switch} /></View>)}</View></View>)}{error ? <Text style={s.error}>{error}</Text> : null}</ScrollView></SafeAreaView>; }
