import { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Check, Search, WalletCards, X } from 'lucide-react-native';
import { formPalette } from './finance-form';
import { walletPresets, type WalletPreset } from '@/constants/wallets';
import { BrandLogo } from '@/components/brand-logo';

export type Wallet = { id: string; name: string; institution_type: string; institution_key: string; balance: number | string; color: string; is_default_cash: boolean; default_outgoing_transfer_fee?: number | string | null; interest_rate?: number | string | null; interest_crediting_frequency?: string | null };

export function WalletPicker({ wallets, value, onChange, required = false, label = 'Wallet' }: { wallets: Wallet[]; value: string | null; onChange: (walletId: string | null) => void; required?: boolean; label?: string }) {
  const [open, setOpen] = useState(false);
  const selected = wallets.find((wallet) => wallet.id === value);
  const displayLabel = label === 'Paid from' ? 'Payment method' : label;
  return <View style={styles.field}><Text style={styles.label}>{displayLabel}{required ? '' : ' (optional)'}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Choose ${displayLabel.toLowerCase()}${selected ? `, ${selected.name}` : ''}`} onPress={() => setOpen(true)} style={styles.trigger}>{selected ? <BrandLogo name={selected.name} entity="wallet" institutionKey={selected.institution_key} category={selected.institution_type} size={30} /> : <View style={[styles.triggerIcon, { backgroundColor: formPalette.accent + '22' }]}><WalletCards size={17} color={formPalette.accent} /></View>}<Text style={[styles.triggerText, !selected && styles.placeholder]}>{selected?.name ?? `Select ${displayLabel.toLowerCase()}`}</Text><Text style={styles.chevron}>›</Text></Pressable><WalletPickerModal visible={open} wallets={wallets} value={value} onClose={() => setOpen(false)} onChange={(id) => { onChange(id); setOpen(false); }} allowUnset={!required} /></View>;
}

export function WalletPickerModal({ visible, wallets, value = null, onClose, onChange, allowUnset, showPresets = false, onPreset }: { visible: boolean; wallets: Wallet[]; value?: string | null; onClose: () => void; onChange: (walletId: string | null) => void; allowUnset: boolean; showPresets?: boolean; onPreset?: (preset: WalletPreset) => void }) {
  const [search, setSearch] = useState('');
  const filtered = useMemo(() => walletPresets.filter((preset) => preset.name.toLowerCase().includes(search.toLowerCase())), [search]);
  const choosePreset = (preset: WalletPreset) => {
    if (onPreset) onPreset(preset);
    else onChange(wallets.find((wallet) => wallet.institution_key === preset.key)?.id ?? null);
  };
  const matchingWallets = wallets.filter((wallet) => wallet.name.toLowerCase().includes(search.toLowerCase()));
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.header}><View><Text style={styles.eyebrow}>MONEY LOCATION</Text><Text style={styles.title}>Choose wallet</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close wallet picker" onPress={onClose} style={styles.close}><X size={20} color={formPalette.ink} /></Pressable></View><View style={styles.search}><Search size={16} color={formPalette.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search banks and e-wallets" placeholderTextColor={formPalette.muted} style={styles.input} /></View><ScrollView contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled">{!showPresets && (matchingWallets.length ? matchingWallets.map((wallet, index) => <WalletChoice key={wallet.id} label={wallet.name} selected={wallet.id === value} showDivider={index < matchingWallets.length - 1} onPress={() => onChange(wallet.id)} />) : <Text style={styles.empty}>No wallets found.</Text>)}{showPresets && ['E-wallets', 'Digital banks', 'Traditional banks'].map((group) => <View key={group}><Text style={styles.group}>{group}</Text>{filtered.filter((preset) => preset.group === group).map((preset) => <WalletChoice key={preset.key} label={preset.name} status={wallets.filter((wallet) => wallet.institution_key === preset.key).length ? `${wallets.filter((wallet) => wallet.institution_key === preset.key).length} added` : undefined} onPress={() => choosePreset(preset)} />)}</View>)}{showPresets && <><Text style={styles.group}>Other</Text><WalletChoice label="Other / Custom" onPress={() => onPreset?.({ key: 'custom', name: 'Other / Custom', type: 'other', color: '#667085', group: 'Other' })} /></>}{allowUnset && <Pressable onPress={() => onChange(null)} style={styles.unset}><Text style={styles.unsetText}>Leave unset</Text></Pressable>}</ScrollView></View></View></Modal>;
}

function WalletChoice({ label, selected = false, status, showDivider = false, onPress }: { label: string; selected?: boolean; status?: string; showDivider?: boolean; onPress: () => void }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`${label} wallet${selected ? ', selected' : ''}`} onPress={onPress} style={({ pressed }) => [styles.choice, showDivider && styles.choiceDivider, selected && styles.choiceSelected, pressed && styles.pressed]}><BrandLogo name={label} entity="wallet" institutionKey={label === 'Other / Custom' ? 'custom' : undefined} size={34} /><Text style={styles.choiceText}>{label}</Text>{status ? <Text style={styles.status}>{status}</Text> : selected ? <Check size={17} color={formPalette.accent} strokeWidth={2.8} /> : <Text style={styles.chevron}>›</Text>}</Pressable>;
}

const styles = StyleSheet.create({ field: { marginTop: 15 }, label: { marginBottom: 8, color: formPalette.muted, fontSize: 11, fontWeight: '900', letterSpacing: 0.4 }, trigger: { minHeight: 52, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, borderRadius: 14, backgroundColor: formPalette.background, borderWidth: 1, borderColor: formPalette.line }, triggerIcon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, triggerText: { flex: 1, marginLeft: 9, color: formPalette.ink, fontSize: 13, fontWeight: '800' }, placeholder: { color: formPalette.muted, fontWeight: '600' }, chevron: { color: formPalette.muted, fontSize: 24, lineHeight: 24 }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,35,28,0.28)' }, sheet: { maxHeight: '88%', padding: 20, borderTopLeftRadius: 26, borderTopRightRadius: 26, backgroundColor: formPalette.surface }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: formPalette.accent, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 }, title: { marginTop: 4, color: formPalette.ink, fontSize: 22, fontWeight: '900' }, close: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: formPalette.background }, search: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 46, marginTop: 16, paddingHorizontal: 12, borderRadius: 13, backgroundColor: formPalette.background, borderWidth: 1, borderColor: formPalette.line }, input: { flex: 1, color: formPalette.ink, fontSize: 13 }, list: { paddingTop: 12, paddingBottom: 24 }, group: { marginTop: 14, marginBottom: 7, color: formPalette.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.1, textTransform: 'uppercase' }, empty: { paddingVertical: 28, color: formPalette.muted, fontSize: 13, fontWeight: '700', textAlign: 'center' }, choice: { minHeight: 58, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9 }, choiceDivider: { borderBottomWidth: 1, borderBottomColor: formPalette.line }, choiceSelected: { backgroundColor: formPalette.accentPale, borderRadius: 12 }, choiceIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 11 }, initials: { color: '#FFFFFF', fontSize: 9, fontWeight: '900' }, choiceText: { flex: 1, marginLeft: 10, color: formPalette.ink, fontSize: 13, fontWeight: '800' }, status: { marginRight: 8, color: formPalette.accent, fontSize: 11, fontWeight: '800' }, unset: { alignItems: 'center', padding: 13 }, unsetText: { color: formPalette.muted, fontSize: 12, fontWeight: '800' }, pressed: { backgroundColor: formPalette.background, opacity: 0.9 } });
