import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ArrowLeft, Bell, ChevronRight, LogOut, Settings, UserCircle, WalletCards } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authenticatedApiRequest } from '@/services/api';
import { getSupabaseClient } from '@/services/supabase';

const p = { background: '#F4F7F1', surface: '#FFFFFF', ink: '#11231C', muted: '#5D6C65', accent: '#0F8A6B', accentPale: '#D8EFE2', line: '#DCE8E0', danger: '#B42318' };
type Profile = { name?: string | null; email?: string | null; avatar_url?: string | null };

export default function ProfileScreen() {
  const [profile, setProfile] = useState<Profile>({});
  useEffect(() => { void authenticatedApiRequest<Profile>('/api/users/me').then(setProfile).catch(() => undefined); }, []);
  const name = profile.name?.trim() || 'Alalay user';
  const initials = name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  const signOut = async () => { await getSupabaseClient()?.auth.signOut(); router.replace('/auth'); };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Back" onPress={() => router.back()} style={styles.back}><ArrowLeft size={22} color={p.ink} /></Pressable><Text style={styles.headerTitle}>Profile</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.profileHeader}>{profile.avatar_url ? <Image source={{ uri: profile.avatar_url }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={styles.initials}>{initials}</Text></View>}<Pressable style={styles.edit}><Text style={styles.editText}>Edit</Text></Pressable><Text style={styles.name}>{name}</Text><Text style={styles.email}>{profile.email || 'Your account email'}</Text></View><Text style={styles.groupLabel}>ACCOUNT</Text><View style={styles.group}><Row icon={UserCircle} label="Profile" value="Personal information" onPress={() => Alert.alert('Profile', 'Profile editing is available from Settings.')} /><Row icon={WalletCards} label="Wallets" value="Banks, e-wallets, and cash" onPress={() => router.push('/(tabs)/wallets')} /><Row icon={Bell} label="Notifications" value="View updates and reminders" onPress={() => router.push('/(tabs)/notifications')} /><Row icon={Settings} label="Settings" value="Preferences and security" onPress={() => router.push('/(tabs)/settings')} /></View><Pressable onPress={() => void signOut()} style={styles.signOut}><LogOut size={19} color={p.danger} /><Text style={styles.signOutText}>Sign out</Text></Pressable></ScrollView></SafeAreaView>;
}

function Row({ icon: Icon, label, value, onPress }: { icon: typeof UserCircle; label: string; value: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.row}><View style={styles.rowIcon}><Icon size={20} color={p.accent} /></View><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View><ChevronRight size={18} color={p.muted} /></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: p.background }, header: { flexDirection: 'row', alignItems: 'center', padding: 18, backgroundColor: p.surface, borderBottomWidth: 1, borderBottomColor: p.line }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, headerTitle: { marginLeft: 8, color: p.ink, fontSize: 23, fontWeight: '900' }, content: { padding: 20, paddingBottom: 38 }, profileHeader: { alignItems: 'center', paddingVertical: 12 }, avatar: { width: 92, height: 92, borderRadius: 46 }, avatarFallback: { width: 92, height: 92, alignItems: 'center', justifyContent: 'center', borderRadius: 46, backgroundColor: p.accent }, initials: { color: '#FFFFFF', fontSize: 28, fontWeight: '900' }, edit: { marginTop: -14, marginLeft: 66, paddingHorizontal: 11, paddingVertical: 6, borderRadius: 14, backgroundColor: p.accentPale }, editText: { color: p.accent, fontSize: 11, fontWeight: '900' }, name: { marginTop: 12, color: p.ink, fontSize: 22, fontWeight: '900' }, email: { marginTop: 4, color: p.muted, fontSize: 13 }, groupLabel: { marginTop: 18, marginBottom: 8, color: p.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 }, group: { overflow: 'hidden', borderRadius: 18, backgroundColor: p.surface, borderWidth: 1, borderColor: p.line }, row: { minHeight: 68, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: p.line }, rowIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: p.accentPale }, rowCopy: { flex: 1, marginLeft: 12 }, rowLabel: { color: p.ink, fontSize: 14, fontWeight: '900' }, rowValue: { marginTop: 3, color: p.muted, fontSize: 11 }, signOut: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 50, marginTop: 22, borderRadius: 25, borderWidth: 1, borderColor: '#F2C6C2', backgroundColor: '#FFF7F6' }, signOutText: { color: p.danger, fontWeight: '900' } });
