import { ActivityIndicator, Alert, Image, Pressable, ScrollView, Text, View } from 'react-native';
import { router, type Href } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Bell, CircleDollarSign, Info, LockKeyhole, Moon, Shield } from 'lucide-react-native';
import Constants from 'expo-constants';
import { getSupabaseClient } from '@/services/supabase';
import { clearMobileTrust } from '@/services/mfa';
import { SettingsHeader, SettingsRow, SettingsSection, useSettingsStyles } from '@/components/settings-ui';
import { useCurrentProfile } from '@/hooks/use-current-profile';
import { getProfileInitials } from '@/services/profile';
import { useAppTheme } from '@/theme/theme';

export default function SettingsScreen() {
  const { colors } = useAppTheme();
  const s = useSettingsStyles();
  const { profile, loading, error, retry } = useCurrentProfile();
  const logout = () => Alert.alert('Log out?', 'You’ll need to sign in again to access your account.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out', style: 'destructive', onPress: () => { void clearMobileTrust().then(() => getSupabaseClient()?.auth.signOut()).then(() => router.replace('/auth')); } }]);
  return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]} edges={['top', 'left', 'right']}><SettingsHeader title="Settings" onBack={() => router.back()} /><ScrollView contentContainerStyle={s.content}>{loading ? <View style={s.loadingState}><ActivityIndicator color={colors.primary} /><Text style={[s.stateText, { color: colors.textSecondary }]}>Loading your profile...</Text></View> : error ? <View style={s.loadingState}><Text style={[s.error, { color: colors.danger }]}>Unable to load your profile.</Text><Pressable accessibilityRole="button" onPress={() => void retry()}><Text style={[s.retry, { color: colors.primary }]}>Retry</Text></Pressable></View> : profile ? <View style={s.profile}>{profile.avatarUrl ? <Image source={{ uri: profile.avatarUrl }} style={s.avatar} /> : <View style={[s.avatarFallback, { backgroundColor: colors.primary }]}><Text style={s.initials}>{getProfileInitials(profile.name)}</Text></View>}<Text style={[s.profileName, { color: colors.textPrimary }]}>{profile.name}</Text><Text numberOfLines={1} style={[s.profileEmail, { color: colors.textSecondary }]}>{profile.email}</Text><Pressable accessibilityRole="button" onPress={() => router.push('/(tabs)/settings/edit-profile' as Href)} style={[s.editButton, { backgroundColor: colors.primarySoft }]}><Text style={[s.editText, { color: colors.primary }]}>Edit Profile</Text></Pressable></View> : null}<SettingsSection title="Preferences"><SettingsRow icon={Moon} label="Appearance" value="" onPress={() => router.push('/(tabs)/settings/appearance')} /><SettingsRow icon={CircleDollarSign} label="Currency" value="PHP (₱)" onPress={() => router.push('/(tabs)/settings/currency')} last /></SettingsSection><SettingsSection title="Notifications"><SettingsRow icon={Bell} label="Notifications" value="Bills, spending, budget, savings" onPress={() => router.push('/(tabs)/settings/notifications')} last /></SettingsSection><SettingsSection title="Security"><SettingsRow icon={Shield} label="Security" value="Password and authenticator" onPress={() => router.push('/(tabs)/settings/security')} last /></SettingsSection><SettingsSection title="About"><SettingsRow icon={Info} label="About" value="Privacy and app information" onPress={() => router.push('/(tabs)/settings/about')} /><SettingsRow icon={LockKeyhole} label="Version" value={Constants.expoConfig?.version || '1.0.0'} onPress={() => undefined} last /></SettingsSection><Pressable accessibilityRole="button" onPress={logout} style={[s.logout, { borderColor: colors.danger + '55', backgroundColor: colors.danger + '12' }]}><Text style={[s.logoutText, { color: colors.danger }]}>Log out</Text></Pressable></ScrollView></SafeAreaView>;
}
