import { ArrowLeft } from "lucide-react";
import { Container } from "../../components/layout/Container";
import { MarketingFooter } from "../../components/layout/MarketingFooter";
import { Navbar } from "../../components/navigation/Navbar";

const sections = [
  ["Information We Collect", "We may collect information you choose to provide, such as your name, email address, financial goals, bills, income, expenses, and messages sent to our support team. We may also receive basic device, usage, and log information needed to operate and improve Alalay. Please review this draft to confirm the categories that apply to your final product."],
  ["How We Use Your Information", "We may use information to provide and personalize Alalay, help you understand your finances, respond to support requests, maintain product security, and improve our services. This draft should be replaced with a description of your actual processing practices before launch."],
  ["Data Storage & Security", "We intend to use reasonable administrative, technical, and organizational safeguards designed to protect information. No online service can promise absolute security. Please replace this placeholder with the specific providers, retention periods, access controls, and incident procedures used by Alalay."],
  ["Third-Party Services", "Alalay may rely on trusted service providers for hosting, authentication, analytics, communications, or AI features. Those providers may process information on our behalf under their own terms. Confirm the provider list and any cross-border processing before publishing this policy."],
  ["Your Rights", "Depending on where you live, you may have rights to access, correct, delete, or receive a copy of your personal information, or to object to certain processing. The process and exceptions depend on applicable law. Please have counsel finalize this section for the locations where Alalay operates."],
  ["Contact Us About Privacy", "For privacy questions or requests, contact us through the Contact page. Update this draft with a monitored privacy contact address and any required legal details before launch."],
];

export function PrivacyPage() {
  return <main className="min-h-screen bg-[#f8f7f2] text-slate-900 dark:bg-[#111a17] dark:text-slate-100"><Navbar /><Container className="py-16 sm:py-24"><a href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#0f8a6b] hover:text-[#0b7359]"><ArrowLeft className="h-4 w-4" /> Back to Alalay</a><div className="mt-10 max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#0f8a6b]">Privacy & trust</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950 dark:text-slate-100 sm:text-5xl">Privacy Policy</h1><p className="mt-4 text-sm text-slate-500 dark:text-slate-400">Last updated: August 2, 2026</p><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-6 text-amber-900 dark:border-amber-700/60 dark:bg-amber-950/30 dark:text-amber-200">Draft for review: this page contains reasonable placeholder template language, not final legal advice. Please review and finalize it with qualified counsel before publishing or relying on it.</div><p className="mt-8 text-lg leading-8 text-slate-600 dark:text-slate-300">Alalay is designed to help you make sense of everyday finances. We want you to understand what information may be used and why. This draft explains our intended approach in plain language.</p><div className="mt-12 space-y-10">{sections.map(([title, copy]) => <section key={title}><h2 className="text-xl font-semibold text-slate-950 dark:text-slate-100">{title}</h2><p className="mt-3 leading-8 text-slate-600 dark:text-slate-300">{copy}</p></section>)}</div></div></Container><MarketingFooter /></main>;
}
